### ISSUE TITLE
showRequired() / required className

### ISSUE THREAD

**Issue by BenIrving** [twisty/formsy-react-components#115]
is there a way to set the required value to work with the showRequired() formsy mixin, so that the asterix is not shown for required fields?

**Comment by twisty** [comment]
Hi, you can hide the asterisk with css:

```css
.required-symbol {
  display: none;
}
```
