### ISSUE TITLE
Validation error not shown when layout=elementOnly

### ISSUE THREAD

**Issue by rodryquintero** [twisty/formsy-react-components#34]
Just noticed this. The error class is applied to the containing div and not the element.

**Comment by twisty** [comment]
Noted. Not sure if this is desired behaviour or not... I really need to relook at the use-case for including the `element-only` layout mode and document it!

**Comment by twisty** [comment]
Going to close this. I think `elementOnly` layout should literally be just that.

You could still get validation classes and errors by using one of the other layouts modes, and then hiding the bits you don't want with CSS.

Example: hide the label

```css
.control-label {
    display: none;
}
```

Hide just the help text:
```css
.help-block {
    display: none;
}
.help-block.validation-message {
    display: inherit;
}
```

Hide just the validation messages:
```css
.help-block.validation-message {
    display: none;
}
```
